import { useCallback, useEffect, useMemo, useState } from 'react'
import type {
  CalledAnalysisResponse,
  CalledResponse,
  FilterCategory,
  FoundChunk,
  IncidentType,
} from '../api/types'
import { useToggleSet } from '../hooks/useToggleSet'

const ALL = 'ALL'

type OpenFilter = 'OPEN' | 'CLOSED' | 'ALL'

/** onlyOpen to send to the backend for each open-filter option. */
const ONLY_OPEN_BY_FILTER: Record<OpenFilter, boolean | undefined> = {
  OPEN: true,
  CLOSED: false,
  ALL: undefined,
}

interface TicketsApiProps {
  selected?: CalledResponse | null
  onSelect?: (called: CalledResponse | null) => void
  /** Tells the app something changed (feedback sent), to refresh the summary. */
  onChange?: () => void
}

export default function TicketsApi({
  selected,
  onSelect,
  onChange,
}: TicketsApiProps = {}) {
  const [calleds, setCalleds] = useState<CalledResponse[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [analyses, setAnalyses] = useState<Record<string, CalledAnalysisResponse>>({})
  const [analyzing, setAnalyzing] = useState<string | null>(null)
  const [feedbackGiven, setFeedbackGiven] = useState<Record<string, boolean>>({})

  const [search, setSearch] = useState('')
  // Open state (open/closed/all) is sent as onlyOpen to the backend — filters at the source
  // (JQL), so it doesn't enter filteredCalleds. Starts at OPEN since it's the most common case.
  const [openFilter, setOpenFilter] = useState<OpenFilter>('OPEN')
  const [statusFilter, setStatusFilter] = useState(ALL)
  const [typeFilter, setTypeFilter] = useState<IncidentType | typeof ALL>(ALL)
  const [categoryFilter, setCategoryFilter] = useState<FilterCategory | typeof ALL>(ALL)

  // Message generated by the analysis, editable before sending to Chatwoot.
  const [messages, setMessages] = useState<Record<string, string>>({})
  const [editing, toggleEditing] = useToggleSet()

  // Sending to Chatwoot still depends on the conversation_id being entered at send time —
  // there's no (yet) automatic mapping between a Jira ticket and a Chatwoot conversation.
  const [showingSend, toggleSend, setShowingSend] = useToggleSet()
  const [conversationIds, setConversationIds] = useState<Record<string, string>>({})
  const [sending, setSending] = useState<Record<string, boolean>>({})
  const [sent, setSent] = useState<Record<string, boolean>>({})
  const [sendError, setSendError] = useState<Record<string, string>>({})

  // Local documentation (keyword search) chunks found during the analysis.
  const [sources, setSources] = useState<Record<string, FoundChunk[]>>({})

  // Status comes from Jira as free text (workflow customized per project) — no fixed enum is
  // possible, so the filter options are derived from what's already loaded.
  const availableStatuses = useMemo(
    () => Array.from(new Set(calleds.map((c) => c.status).filter((s): s is string => !!s))).sort(),
    [calleds],
  )

  const filteredCalleds = useMemo(
    () =>
      calleds.filter((c) => {
        if (statusFilter !== ALL && c.status !== statusFilter) return false
        if (typeFilter !== ALL && c.incidentType !== typeFilter) return false
        if (categoryFilter !== ALL && c.filterCategory !== categoryFilter) return false
        if (search.trim()) {
          const target = search.trim().toLowerCase()
          const matches =
            c.jiraKey.toLowerCase().includes(target) || c.titleCalled.toLowerCase().includes(target)
          if (!matches) return false
        }
        return true
      }),
    [calleds, statusFilter, typeFilter, categoryFilter, search],
  )

  const load = useCallback(
    async (openState: OpenFilter = openFilter) => {
      setLoading(true)
      setError('')
      const r = await window.backendAPI.listCalleds({ onlyOpen: ONLY_OPEN_BY_FILTER[openState] })
      if (r.ok) setCalleds(r.data)
      else setError(r.error)
      setLoading(false)
    },
    [openFilter],
  )

  useEffect(() => {
    load(openFilter)
  }, [openFilter, load])

  const analyze = async (key: string) => {
    setAnalyzing(key)

    // The documentation search doesn't depend on the analysis result (only on the already
    // loaded title/error), so the two calls go out in parallel instead of one waiting for the other.
    const called = calleds.find((c) => c.jiraKey === key)
    const query = [called?.titleCalled, called?.errorName].filter(Boolean).join(' ')
    const [r, rf] = await Promise.all([
      window.backendAPI.analyzeCalled(key),
      query ? window.backendAPI.searchDocumentation(query) : Promise.resolve(null),
    ])

    if (r.ok) {
      setAnalyses((a) => ({ ...a, [key]: r.data }))
      setMessages((m) => ({ ...m, [key]: r.data.solution ?? '' }))
      setSent((e) => ({ ...e, [key]: false }))
      setSendError((e) => ({ ...e, [key]: '' }))
      if (rf?.ok) setSources((f) => ({ ...f, [key]: rf.data }))
    } else {
      setError(r.error)
    }
    setAnalyzing(null)
  }

  const sendFeedback = async (key: string, standardId: string, resolved: boolean) => {
    const r = await window.backendAPI.sendFeedback(key, { standardId, resolved })
    if (r.ok) {
      setFeedbackGiven((f) => ({ ...f, [key]: true }))
      onChange?.()
    } else setError(r.error)
  }

  const discard = (key: string) => {
    setAnalyses((a) => {
      const next = { ...a }
      delete next[key]
      return next
    })
    setShowingSend((s) => {
      const n = new Set(s)
      n.delete(key)
      return n
    })
  }

  const confirmSend = async (key: string) => {
    const conversationId = (conversationIds[key] ?? '').trim()
    if (!conversationId) return
    setSending((e) => ({ ...e, [key]: true }))
    setSendError((e) => ({ ...e, [key]: '' }))
    const r = await window.backendAPI.sendChatwootMessage(conversationId, messages[key] ?? '')
    if (r.ok) {
      setSent((e) => ({ ...e, [key]: true }))
      setShowingSend((s) => {
        const n = new Set(s)
        n.delete(key)
        return n
      })
    } else {
      setSendError((e) => ({ ...e, [key]: r.error }))
    }
    setSending((e) => ({ ...e, [key]: false }))
  }

  return (
    <div className="tickets-api">
      <div className="panel-top">
        <p className="panel-intro">Tickets coming live from Jira.</p>
        <button type="button" onClick={() => load()} disabled={loading}>
          {loading ? '...' : '↻ Refresh'}
        </button>
      </div>

      {error && <p className="notice notice-error">{error}</p>}

      <div className="tickets-filters">
        <select
          value={openFilter}
          onChange={(e) => setOpenFilter(e.target.value as OpenFilter)}
        >
          <option value="OPEN">Open</option>
          <option value="CLOSED">Closed/resolved</option>
          <option value="ALL">All</option>
        </select>

        {calleds.length > 0 && (
          <>
            <input
              type="text"
              placeholder="Search by key or title..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />

            <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
              <option value={ALL}>Status: all</option>
              {availableStatuses.map((s) => (
                <option key={s} value={s}>
                  {s}
                </option>
              ))}
            </select>

            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value as IncidentType | typeof ALL)}
            >
              <option value={ALL}>Type: all</option>
              <option value="ALERT">ALERT</option>
              <option value="ERROR">ERROR</option>
            </select>

            <select
              value={categoryFilter}
              onChange={(e) => setCategoryFilter(e.target.value as FilterCategory | typeof ALL)}
            >
              <option value={ALL}>Category: all</option>
              <option value="SUPPORT">SUPPORT</option>
              <option value="INFRASTRUCTURE">INFRASTRUCTURE</option>
              <option value="DEVELOPMENT">DEVELOPMENT</option>
              <option value="PENDING">PENDING</option>
            </select>
          </>
        )}
      </div>

      {!loading && calleds.length === 0 && !error && (
        <p className="panel-empty">No ticket found for this filter.</p>
      )}

      {!loading && calleds.length > 0 && filteredCalleds.length === 0 && (
        <p className="panel-empty">No ticket matches the filters.</p>
      )}

      <div className="card-list">
        {filteredCalleds.map((c) => {
          const analysis = analyses[c.jiraKey]
          const collapsed = !!analysis
          const hasConfirmedStandard = !!analysis && analysis.confidence !== 'NONE'

          return (
            <div
              key={c.jiraKey}
              className={`item-card ${selected?.jiraKey === c.jiraKey ? 'selected' : ''}`}
              onClick={() =>
                onSelect?.(selected?.jiraKey === c.jiraKey ? null : c)
              }
            >
              <div className="item-card-header">
                <strong>{c.jiraKey}</strong>
                {c.status && <span className="tag">{c.status}</span>}
              </div>

              <p className="item-card-title">{c.titleCalled}</p>
              <div className="item-card-meta">
                {c.routineNumber != null && <span>Routine {c.routineNumber}</span>}
                <span>{c.incidentType}</span>
                <span>{c.filterCategory}</span>
              </div>

              {!collapsed ? (
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation()
                    analyze(c.jiraKey)
                  }}
                  disabled={analyzing === c.jiraKey}
                >
                  {analyzing === c.jiraKey ? 'Analyzing...' : '🔎 Analyze'}
                </button>
              ) : (
                <div className="ticket-result" onClick={(e) => e.stopPropagation()}>
                  <p className="ticket-result-meta">
                    {analysis.method} · score {analysis.score.toFixed(2)} · {analysis.confidence}
                  </p>

                  {editing.has(c.jiraKey) ? (
                    <textarea
                      className="ticket-message-edit"
                      value={messages[c.jiraKey] ?? ''}
                      onChange={(e) =>
                        setMessages((m) => ({ ...m, [c.jiraKey]: e.target.value }))
                      }
                      rows={4}
                    />
                  ) : (messages[c.jiraKey] ?? '').trim() ? (
                    <p className="ticket-message">{messages[c.jiraKey]}</p>
                  ) : (
                    <p className="panel-empty">No solution suggested.</p>
                  )}

                  {(hasConfirmedStandard || (sources[c.jiraKey]?.length ?? 0) > 0) && (
                    <div className="sources-eyebrow">Sources</div>
                  )}

                  {hasConfirmedStandard && (
                    <div className="source">
                      <div className="source-header">
                        <span className="source-name">🟢 Verified standard</span>
                        <span className="tag tag-ok">{analysis.confidence}</span>
                      </div>
                    </div>
                  )}

                  {(sources[c.jiraKey] ?? []).map((f, i) => (
                    <div className="source" key={i}>
                      <div className="source-header">
                        <span className="source-name">
                          🟣 {f.docName}
                          {f.page != null ? ` · pg. ${f.page}` : ''}
                        </span>
                        <span className="source-relevance">{f.relevance}% relevance</span>
                      </div>
                      <p className="source-quote">"{f.text}"</p>
                    </div>
                  ))}

                  <div className="ticket-actions">
                    <button type="button" onClick={() => toggleSend(c.jiraKey)}>
                      📤 Send Webhook to Chatwoot
                    </button>
                    <button
                      type="button"
                      className="btn-secondary"
                      onClick={() => toggleEditing(c.jiraKey)}
                    >
                      {editing.has(c.jiraKey) ? '✓ Done editing' : '✎ Edit message text'}
                    </button>
                    <button
                      type="button"
                      className="btn-secondary"
                      onClick={() => discard(c.jiraKey)}
                    >
                      ✕ Discard
                    </button>
                  </div>

                  {showingSend.has(c.jiraKey) && (
                    <div className="ticket-send-form">
                      <input
                        type="text"
                        placeholder="Chatwoot conversation_id"
                        value={conversationIds[c.jiraKey] ?? ''}
                        onChange={(e) =>
                          setConversationIds((ids) => ({ ...ids, [c.jiraKey]: e.target.value }))
                        }
                      />
                      <button
                        type="button"
                        onClick={() => confirmSend(c.jiraKey)}
                        disabled={
                          sending[c.jiraKey] || !(conversationIds[c.jiraKey] ?? '').trim()
                        }
                      >
                        {sending[c.jiraKey] ? 'Sending...' : 'Confirm send'}
                      </button>
                      <button
                        type="button"
                        className="btn-secondary"
                        onClick={() => toggleSend(c.jiraKey)}
                      >
                        Cancel
                      </button>
                    </div>
                  )}

                  {sent[c.jiraKey] && (
                    <p className="notice notice-ok">Message sent to Chatwoot.</p>
                  )}
                  {sendError[c.jiraKey] && (
                    <p className="notice notice-error">{sendError[c.jiraKey]}</p>
                  )}

                  {analysis.standardId &&
                    (feedbackGiven[c.jiraKey] ? (
                      <p className="notice notice-ok">Feedback recorded. Thank you!</p>
                    ) : (
                      <div className="feedback-buttons">
                        <span>Did it resolve it?</span>
                        <button
                          type="button"
                          onClick={() => sendFeedback(c.jiraKey, analysis.standardId!, true)}
                        >
                          👍 Yes
                        </button>
                        <button
                          type="button"
                          className="btn-secondary"
                          onClick={() => sendFeedback(c.jiraKey, analysis.standardId!, false)}
                        >
                          👎 No
                        </button>
                      </div>
                    ))}
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
